"""empty message

Revision ID: 759b8ed0dedd
Revises: 
Create Date: 2020-06-21 11:18:04.868255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759b8ed0dedd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=108), nullable=False),
    sa.Column('avator', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.String(length=32), nullable=False),
    sa.Column('login_time', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(length=32), nullable=False),
    sa.Column('img', sa.String(length=64), nullable=True),
    sa.Column('detail_info', sa.Text(), nullable=True),
    sa.Column('create_time', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('admin')
    # ### end Alembic commands ###
